name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: 构建 Windows 包
      run: go build -ldflags="-s -w -H windowsgui" ./client/main.go
    - name: 重命名构建文件
      run: mv ./main ./main.exe

    - name: 上传 EXE
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: 构建成品
        # A file, directory or wildcard pattern that describes what to upload
        path: .
